######################################################################
#
# File name : tb_hs_dual_da_wave.do
# Created on: Wed Jun 14 10:37:05 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
