######################################################################
#
# File name : tb_hs_dual_da_compile.do
# Created on: Tue Jun 20 14:26:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../hs_dual_da.gen/sources_1/ip/clk_wiz_0" \
"../../../../hs_dual_da.gen/sources_1/ip/rom_1024x10b/sim/rom_1024x10b.v" \
"../../../../hs_dual_da.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../hs_dual_da.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/da_wave_send.v" \
"../../../../../rtl/hs_dual_da.v" \
"../../../../../sim/tb/tb_hs_dual_da.v" \


# compile glbl module
D:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

