######################################################################
#
# File name : tb_hs_dual_da_simulate.do
# Created on: Tue Jun 20 14:26:26 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_hs_dual_da xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_hs_dual_da_wave.do}

view wave
view structure
view signals

do {tb_hs_dual_da.udo}

run 1000ns
