# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/senhaowang/project/33_hs_dual_da/prj/hs_dual_da.srcs/sources_1/ip/rom_1024x10b/rom_1024x10b.xci
# IP: The module: 'rom_1024x10b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/senhaowang/project/33_hs_dual_da/prj/hs_dual_da.gen/sources_1/ip/rom_1024x10b/rom_1024x10b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_1024x10b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/senhaowang/project/33_hs_dual_da/prj/hs_dual_da.srcs/sources_1/ip/rom_1024x10b/rom_1024x10b.xci
# IP: The module: 'rom_1024x10b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/senhaowang/project/33_hs_dual_da/prj/hs_dual_da.gen/sources_1/ip/rom_1024x10b/rom_1024x10b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_1024x10b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
